services:
  # A web service
  - type: web
    name: beyond-hunger
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn beyond_hunger.wsgi --workers 3"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: WEB_CONCURRENCY
        value: 3
      - key: PYTHON_VERSION
        value: 3.12.8 