# Generated by Django 5.1.7 on 2025-04-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0003_marketplaceitem_marketplacelister'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_donations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_donation.fooddonation')),
            ],
        ),
        migrations.CreateModel(
            name='IDVerificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='id_verification/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_images', to='food_donation.marketplacelister')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/multi/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_donation.marketplaceitem')),
            ],
        ),
    ]
