# Generated by Django 5.1.7 on 2025-04-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0006_alter_languagepreference_language_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='languagepreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='LanguagePreference',
        ),
    ]
