# Generated by Django 5.1.7 on 2025-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0009_fooddonation_is_hidden_moneydonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('food_donation', 'Food Donation'), ('money_donation', 'Money Donation'), ('volunteer', 'Volunteer'), ('marketplace', 'Marketplace'), ('account', 'Account'), ('general', 'General Information'), ('technical', 'Technical'), ('fallback', 'Fallback')], max_length=50)),
                ('keywords', models.TextField(help_text='Comma-separated keywords that trigger this response')),
                ('question', models.TextField(help_text='Example question that would trigger this response')),
                ('response', models.TextField(help_text="The chatbot's response")),
                ('priority', models.IntegerField(default=0, help_text='Higher priority responses will be chosen over lower ones when multiple keywords match')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'category'],
            },
        ),
    ]
