# Generated by Django 5.0.14 on 2025-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0017_moneydonation_notes_moneydonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhandara',
            name='expected_attendees',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated number of people expected to attend', null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='organizer_type',
            field=models.CharField(blank=True, help_text='E.g., Individual, Organization, Temple, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special instructions for attendees', null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='volunteer_tasks',
            field=models.TextField(blank=True, help_text='Description of tasks volunteers will perform', null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='volunteers_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of volunteers needed for this event', null=True),
        ),
        migrations.AddField(
            model_name='bhandara',
            name='volunteers_needed',
            field=models.BooleanField(default=False),
        ),
    ]
