# Generated by Django 5.0.14 on 2025-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0018_bhandara_expected_attendees_bhandara_organizer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonation',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN number for tax benefits', max_length=10, null=True),
        ),
    ]
