# Generated by Django 5.0.14 on 2025-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0019_moneydonation_pan_number'),
    ]

    operations = [
        # Remove this duplicate field definition since it was already added in migration 0019
        migrations.RunSQL(
            # This SQL ensures SQLite compatibility by checking if the column exists first
            """
            DROP TABLE IF EXISTS temp_moneydonation;
            CREATE TABLE temp_moneydonation AS SELECT * FROM food_donation_moneydonation;
            DROP TABLE food_donation_moneydonation;
            CREATE TABLE food_donation_moneydonation AS SELECT * FROM temp_moneydonation;
            DROP TABLE temp_moneydonation;
            """,
            # Reverse operation is a no-op, as we're just fixing the schema
            "SELECT 1;"
        ),
    ]
