# Generated by Django 5.0.14 on 2025-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0020_auto_20250415_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneydonation',
            name='pan_number',
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information including tax certificate requests', null=True),
        ),
    ]
