# Generated by Django 5.0.14 on 2025-04-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0021_remove_pan_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonation',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank details for donation transfer', null=True),
        ),
        migrations.AddField(
            model_name='moneydonation',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for easy payment', null=True, upload_to='qr_codes/'),
        ),
    ]
