# Generated by Django 5.0.14 on 2025-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_donation', '0022_moneydonation_bank_details_moneydonation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydonation',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN number for tax benefit certificates', max_length=10, null=True),
        ),
    ]
