name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    outputs:
      has_secrets: ${{ steps.check.outputs.has_secrets }}
    steps:
      - id: check
        run: |
          if [ "${{ secrets.PYTHONANYWHERE_API_TOKEN }}" != '' ] && [ "${{ secrets.PYTHONANYWHERE_USERNAME }}" != '' ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi
          
  deploy:
    needs: check_secrets
    if: needs.check_secrets.outputs.has_secrets == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # Create a more robust deploy script
        cat > deploy_script.py << 'EOF'
        import os
        import requests
        import sys
        import time

        username = os.environ.get('PA_USERNAME')
        token = os.environ.get('PA_API_TOKEN')

        if not username or not token:
            print('Error: Environment variables PA_USERNAME and PA_API_TOKEN must be set')
            sys.exit(1)

        # Check if webapp exists first
        print(f'Checking for webapp {username}.pythonanywhere.com...')
        check_url = f'https://www.pythonanywhere.com/api/v0/user/{username}/webapps/'
        check_response = requests.get(
            check_url,
            headers={'Authorization': f'Token {token}'}
        )
        
        if check_response.status_code != 200:
            print(f'Error checking webapps: {check_response.status_code}')
            print(f'Response: {check_response.text}')
            sys.exit(1)
            
        webapps = check_response.json()
        webapp_exists = False
        for webapp in webapps:
            if webapp.get('domain_name') == f'{username}.pythonanywhere.com':
                webapp_exists = True
                break
                
        if not webapp_exists:
            print(f'Error: Webapp {username}.pythonanywhere.com does not exist on PythonAnywhere')
            print('Please create the webapp first following the deployment guide')
            sys.exit(1)

        # Now proceed with reload
        print('Deploying to PythonAnywhere...')
        reload_url = f'https://www.pythonanywhere.com/api/v0/user/{username}/webapps/{username}.pythonanywhere.com/reload/'
        print(f'POST request to: {reload_url}')
        
        # Add retry logic
        max_attempts = 3
        for attempt in range(1, max_attempts + 1):
            try:
                response = requests.post(
                    reload_url,
                    headers={'Authorization': f'Token {token}'}
                )
                
                if response.status_code == 200:
                    print('Deployment successful!')
                    sys.exit(0)
                else:
                    print(f'Deployment attempt {attempt} failed: {response.status_code}')
                    print(f'Response text: {response.text}')
                    
                    if attempt < max_attempts:
                        print(f'Retrying in {attempt * 2} seconds...')
                        time.sleep(attempt * 2)
                    else:
                        print('All retry attempts failed')
                        sys.exit(1)
            except Exception as e:
                print(f'Exception during deployment attempt {attempt}: {str(e)}')
                if attempt < max_attempts:
                    print(f'Retrying in {attempt * 2} seconds...')
                    time.sleep(attempt * 2)
                else:
                    print('All retry attempts failed')
                    sys.exit(1)
        EOF
        
        python deploy_script.py 