name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # Create a simple deploy script
        cat > deploy_script.py << 'EOF'
        import os
        import requests

        username = os.environ.get('PA_USERNAME')
        token = os.environ.get('PA_API_TOKEN')

        if not username or not token:
            print('Error: Environment variables PA_USERNAME and PA_API_TOKEN must be set')
            exit(1)

        print('Deploying to PythonAnywhere...')
        response = requests.post(
            f'https://www.pythonanywhere.com/api/v0/user/{username}/webapps/{username}.pythonanywhere.com/reload/',
            headers={'Authorization': f'Token {token}'}
        )

        if response.status_code == 200:
            print('Deployment successful!')
        else:
            print(f'Deployment failed: {response.status_code} {response.text}')
            exit(1)
        EOF
        
        python deploy_script.py 